[helpers]

[default]
depends = []

[default.files]
alacritty = "~/.config/alacritty/alacritty.yml"
coc-settings = "~/.config/nvim/coc-settings.json"
condarc = "~/.condarc"
fastfetch = "~/.config/fastfetch/config.conf"
gzdoom = "~/.config/gzdoom/gzdoom.ini"
neovim = "~/.config/nvim/init.vim"
ranger = "~/.config/ranger/rc.conf"
ranger_commands = "~/.config/ranger/commands.py"
ranger_commands_full = "~/.config/ranger/commands_full.py"
rifle = "~/.config/ranger/rifle.conf"
rifle_scope = "~/.config/ranger/scope.sh"
tmux = "~/.tmux.conf"
zshrc = "~/.zshrc"

[default.variables]
